include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - string_literal_finder

string_literal_finder:
  exclude_globs:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/firebase_options.dart"
