name: smart_shopping
description: A new Flutter project.
publish_to: "none"
version: 0.3.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  build_runner: ^2.4.8
  cloud_firestore: ^4.14.0
  dartz: ^0.10.1
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.5.7
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_riverpod: ^2.4.10
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.6
  riverpod_annotation: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.11
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9
  flutter_launcher_icons: "^0.13.0"
  string_literal_finder: ^1.3.0+2

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/icon_background.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"
