// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCTLWknPd78ZUPCt6KZXKxLHF3Y49kCg',
    appId: '1:965094397120:android:70a4ab7117fbac825c0925',
    messagingSenderId: '965094397120',
    projectId: 'smart-shopping-fa064',
    storageBucket: 'smart-shopping-fa064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQTPWbxDaWspvDtUhjLsCeb_UqYUvxfk',
    appId: '1:965094397120:ios:f67926dbe01a7aef5c0925',
    messagingSenderId: '965094397120',
    projectId: 'smart-shopping-fa064',
    storageBucket: 'smart-shopping-fa064.appspot.com',
    androidClientId: '965094397120-1disucemhfbnbqmfjqdcc2h6o8thb3du.apps.googleusercontent.com',
    iosClientId: '965094397120-md4vbuv51thd2ojmpar7pcmsdcra4d4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartShopping',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1Q6SSnh3hbDI2uxOvI43mOc8rWYb6Fg',
    appId: '1:965094397120:web:a89b326b6a8fe7575c0925',
    messagingSenderId: '965094397120',
    projectId: 'smart-shopping-fa064',
    authDomain: 'smart-shopping-fa064.firebaseapp.com',
    storageBucket: 'smart-shopping-fa064.appspot.com',
    measurementId: 'G-KMREEHCT5L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPQTPWbxDaWspvDtUhjLsCeb_UqYUvxfk',
    appId: '1:965094397120:ios:f67926dbe01a7aef5c0925',
    messagingSenderId: '965094397120',
    projectId: 'smart-shopping-fa064',
    storageBucket: 'smart-shopping-fa064.appspot.com',
    androidClientId: '965094397120-1disucemhfbnbqmfjqdcc2h6o8thb3du.apps.googleusercontent.com',
    iosClientId: '965094397120-md4vbuv51thd2ojmpar7pcmsdcra4d4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartShopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC1Q6SSnh3hbDI2uxOvI43mOc8rWYb6Fg',
    appId: '1:965094397120:web:95adc01e1b7dd3095c0925',
    messagingSenderId: '965094397120',
    projectId: 'smart-shopping-fa064',
    authDomain: 'smart-shopping-fa064.firebaseapp.com',
    storageBucket: 'smart-shopping-fa064.appspot.com',
    measurementId: 'G-EBWFVF86YR',
  );

}